version: '3.1'
services:
  postgres:
    image: postgres:9.6
    ports:
      - 5437:5432
    restart: always
    environment:
      POSTGRES_USER: dataloader
      POSTGRES_PASSWORD: yaya
      POSTGRES_DB: dataloader
